project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/login', function () {
    return view('auth/login');
});

Route::get('/register', function () {
    return view('auth/register');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/settings', 'UserController@index')->name('settings')->middleware('auth');
Route::get('/categories', 'CategoryController@index')->name('categories')->middleware('auth');
Route::get('/shareds', 'HomeController@shareds')->name('shareds')->middleware('auth');


Route::get('/reports/lastmonth', 'ReportsController@lastmonth')->name('LM')->middleware('auth');
Route::get('/reports/between', 'ReportsController@between_two_dates')->name('BTD')->middleware('auth');
Route::get('/reports/last_year', 'ReportsController@lastyear')->name('LY')->middleware('auth');

Route::post('/reports/between', 'ReportsController@loadBetween')->name('loadbetween')->middleware('auth');
Route::post('/reports/lastmonth', 'ReportsController@search_by_month')->name('lastmonth')->middleware('auth');
Route::post('/reports/last_year', 'ReportsController@search_by_year')->name('lastyear')->middleware('auth');
Route::post('/transactions', 'TransactionController@store')->middleware('auth');



Route::resource('/allows', 'UserAllowedController')->middleware('auth');
Route::resource('/accounts', 'AccountController')->middleware('auth');
Route::resource('/categories', 'CategoryController')->middleware('auth');
Route::resource('/currencies', 'CurrencyController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/local_currencies', 'SetCurrenciesController')->middleware('auth');
Route::resource('/graph', 'GraphController')->middleware('auth');


Route::get('/share', function (Request $request) {
    return view('accounts.share');
})->name('share')->middleware('auth');
Route::get('/loading', function () {
return view('layouts.loader');
})->name('loading')->middleware('auth');

project/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = false;
    protected $fillable = ['id_user', 'id_account', 'id_parent', 'id_type', 'name', 'description', 'active'];
}

project/app/Models/CategoryType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CategoryType extends Model
{
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['id', 'description'];
}

project/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\CategoryType;
use App\Models\Category;
use App\Http\Requests\CategoryRequest;
use Auth;

class CategoryController extends Controller{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();
        $categories_type = CategoryType::get();
        return view('categories.create', compact('categories'), compact('categories_type'));
    }

     /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $user = Auth::User();
        $category = new Category();
        $category->name = $request->input('name');
        $category->description = $request->input('description');
        $category->id_parent = $request->input('id_parent') ?? null;
        $category->id_account = $request->input('id_account') ?? null;
        if ($request->input('id_parent')) {
            $cat = Category::where('id', $request->input('id_parent'))->first();
            $category->id_type = $cat->id_type;
        } else {
            $category->id_type = $request->input('id_type');
        }
        $category->active = 'true';
        $category->id_user = $user->id;
        $category->save();
        if ($request->id_parent) {
            return redirect()->route('categories.show', $request->id_parent)
                ->with('warning', 'La subcategoria ha sido creada con exito!');
        } else {
            return redirect()->route('accounts.show', $request->id_account)
                ->with('warning', 'La categoria ha sido creada con exito!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::where('id', $id)->firstOrFail();
        $type = CategoryType::where('id', $category->id_type)->first();
        $categories_type = CategoryType::get();
        $user = Auth::User();
        $categories = Category::where([
            ['id_parent', $category->id],
            ['id_user', $user->id],
            ['active', true]
        ])->get();
        return view('categories.show', compact('categories', 'category', 'categories_type', 'type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::where('id', $id)->firstOrFail();
        $category->update($request->all());
        $category->save();
        return redirect('accounts/' . $category->id_account);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::where('id', $id)->firstOrFail();
        $category->active = false;
        $category->update();
        return redirect('home')->with('message', 'Your account was deleted');
    }
}

project/resources/views/categories/categorie.blade.php
@extends('layouts.app')
@section('content')

<header>
    <link href="{{ asset('css/show.css') }}" rel="stylesheet">
</header>

<div class="container">
    <div class="row">
      <div class="col-sm-9">
        <br>
        <h1 class="info text-b">{{ $account->name }}
          <span class="badge
            badge-success">Saldo Actual</span></h1>
        <h6 class="info text-b">Verde si es positivo, rojo si es negativo</h6>
      </div>
    </div>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{  route('accounts.show', $account->id) }}">Home</a></li>
        <li class="breadcrumb-item"><a href="#">Library</a></li>
        <li class="breadcrumb-item"><a href="#">Data</a></li>
      </ol>
    </nav>

    <div class="row">
      <div class="col-sm-3">
        <ul class="list-group">
          <li class="list-group-item text-muted"><i class="fa fa-info-circle
              fa-1x"></i>&nbsp;&nbsp;Información</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Moneda</strong></span>
            {{ $currency->description }}</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Saldo inicial</strong></span> {{ $account->initial_balance }}</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Saldo</strong></span> Calcular</li>

        </ul>
        <br>
        <ul class="list-group">
          <li class="list-group-item text-muted"><i class="fa fa-dashboard
              fa-1x"></i>&nbsp;&nbsp;Activity</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Compartidos</strong></span>
            # shares</li>
          <li class="list-group-item text-right"><span class="pull-left"><strong>Transacciones</strong></span>
            # transacciones</li>
        </ul>
        <br>
        <ul class="list-group">
          <li class="list-group-item text-muted"><i class="fa fa-money
              fa-1x"></i>&nbsp;&nbsp;Moneda</li>
          <li class="list-group-item text-right"><span
              class="pull-left"><strong>Nombre</strong></span>
              {{ $currency->name }}</li>
          <li class="list-group-item text-right"><span
            class="pull-left"><strong>Simbolo</strong></span>
              {{ $currency->symbol }}</li>
        </ul>
      </div>

      <div class="col-sm-9">
        &nbsp;
        <ul class="nav nav-tabs">
          <li class="nav-item active"><a href="#categories" class="nav-link
              active"
              data-toggle="tab"><i class="fa fa-folder
                fa-1x"></i>&nbsp; Categorias</a></li>
          <li class="nav-item active"><a href="#transaction" class="nav-link"
              data-toggle="tab"><i class="fa fa-exchange
                fa-1x"></i>&nbsp; Transacciones</a></li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane active" id="categories">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr class="text-b">
                    <th>Parent</th>
                    <th>Type</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody id="items">
                  <tr data-toggle="modal"
                    data-target="#imageModal" class="text-b">
                    <td>image des</td>
                   
                    <td>
                      <span class="badge
                        badge-success">tag</span>
                    </td>
                    <td>
                      Private
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <hr>
          </div>

          <div class="tab-pane" id="transactions">
            <br>
            <div class="container">
              <input *ngIf="userStatus" type="checkbox" checked
                data-md-icheck (change)="userState($event)" />
              <input *ngIf="!userStatus" type="checkbox"
                data-md-icheck (change)="userState($event)" />
              <span> modo incognito</span>
              &nbsp;
              <button type="submit" (click)="changeMode()"
                class="btn btn-primary">Cambiar modo</button>
            </div>
            <br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Tags</th>
                  </tr>
                </thead>
                <tbody id="items">
                  <tr>
                  </tr>
                </tbody>
              </table>
            </div>
            <hr>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

project/resources/views/categories/create.blade.php
@extends('layouts.app')
@section('content')

<div class="row h-75 justify-content-center align-items-center">
        <form method="POST" action="{{ route('categories.store') }}">
            @csrf
            <div class="form-group">
                <input type="hidden" name="id_parent" value="">
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Tipo de categoria:</label>
                <select name="type_category" id="type_category">
                @foreach($categories_type as $val)
                    <option required value = '{{ $val->id }}' >{{$val->description}}</option>
                    @empty($categories_type)
                        <option value="">No hay datos disponibles</option>
                    @endempty
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Descripción:</label>
                <input type="text" class="form-control"required name="description" id="description">
                <input type="hidden" name="id_account" required value="{{ app('request')->input('id') }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-info">Crear categoria</button>
            <button type="button" class="btn btn-lg btn-danger"><a href="{{route('home')}}">Cancelar</a></button>
            </div>
        </form>
    </div>
@endsection

project/resources/views/categories/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="container-fluid" >
      <div class="row">
          <div class="col-md-4">
           <h3>Categorias de {{$category->name}}</h3>
          </div>
          <div class="col-md-4">
          </div>
          @if ( $category->id_user == Auth::User()->id )
              <div class="col-md-4">
              <a href="" class="btn-lg  btn-success" data-toggle="modal" data-target="#editCategory">Editar</a>
              <a href="" class="btn-lg  btn-danger" data-toggle="modal" data-target="#deleteCategory">Eliminar</a>
              <a href="" class="btn-lg  btn-primary" data-toggle="modal" data-target="#createSub">Crear categoria</a>
             </div> 
                <div class="container">  <br>
                  <div class="card-group owner">
                      <div class="row">
                             @forelse ($categories as $own)
                  <a href="{{ route('categories.show', $own->id) }}" class="card text-center">
                      <div class="card-header">
                          <h5>{{ $own->description }}</h5>
                      </div>
                  </a>
              &nbsp;
              @empty
              <div class="empty">
                  <h4 class="container-title">No hay datos disponibles</h4>
              </div>            
              @endforelse
                      </div>
                  </div>
              </div>
          @else
          @endif  
      </div>
  </div>

  <!-- Modal to create subcategories-->
  <div class="modal fade" id="createSub" tabindex="-1" role="dialog" aria-labelledby="createSub" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">  
        <div class="modal-body">
         <form method="POST" action="{{ route('categories.store') }}">
            @csrf
            <div class="form-group">
                <label for="id_type">Tipo:</label>
                <br>
                <select disabled class="form-control" name="id_type">
                    <option value = '{{ $type->id }}' >{{$type->description}}</option>
                </select>
            </div>
            <div class="form-group">
                <label for="name">Nombre:</label>
                <input required type="text" class="form-control" name="name" id="name">
            </div>
            <div class="form-group">
                <label for="description">Descripción:</label>
                <textarea cols="30" rows="10" type="text" class="form-control" name="description" id="description"></textarea>
                <input type="hidden" id="id_account" name="id_account" value="{{ $category->id_account }} ">
                <input type="hidden" id="id_parent" name="id_parent" value="{{ $category->id }} ">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-info">Crear</button>
                <button type="button" class="btn btn-lg btn-danger"><a href="{{ route('home') }}">Cancelar</a></button>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal to edit Categories -->
<div class="modal fade" id="editCategory" tabindex="-1" role="dialog" aria-labelledby="editCategory" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">  
        <div class="modal-body">
         <form method="POST" action="{{ route('categories.update',$category->id) }}">
              @csrf
              @method('PUT')
            <div class="form-group">
                <label for="formGroupExampleInput">Tipo:</label>
                <br>
                <select disabled class="form-control">
                    <option value = '{{ $type->id }}' >{{$type->description}}</option>
                </select>
            </div>
            <div class="form-group">
                <label for="name">Nombre:</label>
                <input required type="text" class="form-control" name="name" id="name" value="{{ $category->name }}">
            </div>
            <div class="form-group">
                <label for="description">Descripción:</label>
                <textarea cols="30" rows="10" type="text" class="form-control" name="description" id="description">{{ $category->description }}</textarea>
                <input type="hidden" name="id" value="{{ $category->id_account }} ">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-info">Actualizar</button>
                <button type="button" class="btn btn-lg btn-danger" data-dismiss="modal">Cancelar</a></button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


 <!--Modal to confirm the deletion of Category-->
  <div class="modal fade" id="deleteCategory" tabindex="-1" role="dialog" aria-labelledby="deleteCategory" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          
        <h5 class="modal-title" id="exampleModalLabel">{{$category->description}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        ¿De verdad quieres eliminar esta cuenta?
        </div>
        <div class="modal-footer">
            <form action="{{ route('categories.destroy', $category->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <button class="btn btn-success" type="submit">Confirmar</button>
              <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </form>
        </div>
      </div>
    </div>
  </div>
  @endsection