project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/login', function () {
    return view('auth/login');
});

Route::get('/register', function () {
    return view('auth/register');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/settings', 'UserController@index')->name('settings')->middleware('auth');
Route::get('/categories', 'CategoryController@index')->name('categories')->middleware('auth');
Route::get('/shareds', 'HomeController@shareds')->name('shareds')->middleware('auth');


Route::get('/reports/lastmonth', 'ReportsController@lastmonth')->name('LM')->middleware('auth');
Route::get('/reports/between', 'ReportsController@between_two_dates')->name('BTD')->middleware('auth');
Route::get('/reports/last_year', 'ReportsController@lastyear')->name('LY')->middleware('auth');

Route::post('/reports/between', 'ReportsController@loadBetween')->name('loadbetween')->middleware('auth');
Route::post('/reports/lastmonth', 'ReportsController@search_by_month')->name('lastmonth')->middleware('auth');
Route::post('/reports/last_year', 'ReportsController@search_by_year')->name('lastyear')->middleware('auth');
Route::post('/transactions', 'TransactionController@store')->middleware('auth');



Route::resource('/allows', 'UserAllowedController')->middleware('auth');
Route::resource('/accounts', 'AccountController')->middleware('auth');
Route::resource('/categories', 'CategoryController')->middleware('auth');
Route::resource('/currencies', 'CurrencyController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/local_currencies', 'SetCurrenciesController')->middleware('auth');
Route::resource('/graph', 'GraphController')->middleware('auth');


Route::get('/share', function (Request $request) {
    return view('accounts.share');
})->name('share')->middleware('auth');
Route::get('/loading', function () {
return view('layouts.loader');
})->name('loading')->middleware('auth');

project/app/Models/TransactionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TransactionType extends Model
{
    public $timestamps = false;
    protected $fillable = ['id', 'description'];
}

project/app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Transaction;
use App\Models\Account;
use App\Models\TransactionType;
use App\Models\Category;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Auth;

class TransactionController extends Controller{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = Auth::User();
        $categoriesI = Category::where([['id_user', $user->id], ['id_type', 1], ['active', true]])->get();
        $categoriesS = Category::where([['id_user', $user->id], ['id_type', 2], ['active', true]])->get();
        $account = Account::where('id', $request->input('idac'))->first();
        $transactions_type = TransactionType::get();
        $accounts = Account::where([['id_owner', $user->id], ['id', '!=', $request->input('idac')]])->get();
        return view('transactions.create', compact('accounts', 'transactions_type', 'account', 'categoriesI', 'categoriesS'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $account                    = Account::where('id', $request->account)->first();
        $current_timestamp          = date('d-m-Y');
        $transaction                = new Transaction();
        $transaction->id_type       = request('transaction_type');
        $transaction->id_account     = request('account');
        if (request('categoryI')) {
            $transaction->id_category   = request('categoryI');
        }else {
            $transaction->id_category   = request('categoryS');
        }
        $transaction->amount        = $current_timestamp;
        $transaction->amount        = request('amount');
        $transaction->detail        = $request->input('description');

        if ($request->transaction_type == 1 && $account) {
            $transaction->save();
            DB::table('accounts')->where('accounts.id', $request->account)->increment('initial_balance', $request->amount);
            return redirect('accounts/' . $request->account)->with('success', 'Tu transaccion se realizo!');
        } else if ($request->transaction_type == 2 && $account) {
            if (request('amount') < $account->initial_balance) {
                $transaction->save();
                DB::table('accounts')->where('accounts.id', $request->account)->decrement('initial_balance', $request->amount);
                return redirect('accounts/' . $request->account)->with('success', 'Tu transaccion se realizo!');
            } else {
                return back()->with('error', 'El monto de la transacción es mayor que el saldo permitido!');
            }
        } else {
            $transaction2               = new Transaction();
            $transaction2->id_type      = 1;
            $transaction2->id_account   = request('accountO');
            $transaction2->id_category  = request('category');
            $transaction2->amount       = $current_timestamp;
            $transaction2->amount       = request('amount');
            $transaction2->detail       = $request->input('description');
            if (request('amount') < $account->initial_balance) {
                $transaction->id_type = 2;
                $transaction->save();
                $transaction2->save();
                DB::table('accounts')->where('accounts.id', $request->accountO)->increment('initial_balance', $request->amount);
                DB::table('accounts')->where('accounts.id', $request->account)->decrement('initial_balance', $request->amount);
                return redirect('accounts/' . $request->account)->with('success', 'Tu transaccion se realizo!');
            } else {
                return back()->with('error', 'El monto de la transacción es mayor que el saldo permitido!');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::User();
        $transactions_type = TransactionType::get();
        $transaction = Transaction::where('id', $id)->firstOrFail();
        $accounts = Account::where('id_owner', $user->id)->get();
        return view('transactions.show', compact('transaction', 'accounts', 'transactions_type'));
    }

      /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $transaction = Transaction::where('id', $id)->firstOrFail();
        $transaction->update($request->all());
        $transaction->save();
        return redirect('home')->with('success', 'Tu transaccion se realizo!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transaction::where('id', $id)->firstOrFail();
        $transaction->active = false;
        $transaction->update();
        return redirect('home')->with('success', 'Your transaction was deleted!');
    }
}

project/resources/views/transactions/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
<h1>{{ $account->name }}</h1>
<div class="row h-75 justify-content-center align-items-center">
    <form method="POST" action="{{ route('transactions.store') }}">
        @csrf
        <div class="form-group">
            <label for="transaction_type">Seleccione el tipo de transacción:</label>
            <select class="form-control" required name="transaction_type" id="transaction_type">
                @forelse ($transactions_type as $type)
                    <option value="{{$type->id}}">{{$type->description}}</option>
                @empty
                    <option value="">No hay datos disponibles</option>
                @endforelse
            </select>
        </div>
        
        <div class="form-group" id="accounts">
            <label id="accountOt"  for="accountO">Seleccione la cuenta:</label>
            <select class="form-control" required name="accountO" id="accountO">
                @forelse ($accounts as $account)
                    <option value="{{$account->id}}">{{$account->name}}</option>
                @empty
                    <option value="">No hay datos disponibles</option>
                @endforelse
            </select>
        </div>
        <div class="form-group" id="categoryI">
            <label id="categoryI"  for="categories">Categoria:</label>
            <select class="form-control" name="categoryI" id="categoryI">
                @forelse ($categoriesI as $categoryI)
                    <option value="{{$categoryI->id}}">{{$categoryI->name}}</option>
                @empty
                    <option value="">No hay datos disponibles</option>
                @endforelse
            </select>
        </div>
        <div class="form-group">
            <label for="amount">Monto:</label>
            <br>
            <input class="form-control" required type="number" name="amount" id="amount">
            <input class="form-control" type="hidden" name="account" id="account" value="{{app('request')->input('idac')}}">
        </div>
        <div class="form-group">
            <label for="description">Descripción:</label>
            <textarea class="form-control" type="text" name="description" id="description" cols="30" rows="10" required></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-info">Crear</button>
            <a class="btn btn-lg btn-danger" href="{{ route('home') }}">Cancelar</a>
        </div>
    </form>
</div>
<footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{{ asset('js/create-transaction.js') }}" defer></script>
</footer>
</div>
@endsection 

project/resources/views/transactions/index.blade.php
@extends('layouts.app')
@section('content')

@endsection

project/resources/views/transactions/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="container-fluid" >
      <div class="row">
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
          </div>
          
              <div class="col-md-4">
              <a href="" class="btn-lg  btn-success" data-toggle="modal" data-target="#editTransaction">Editar</a>
              <a href="" class="btn-lg  btn-danger" data-toggle="modal" data-target="#deleteTransaction">Eliminar</a>
             </div> 
      </div>
  </div>


<!--Modal to edit transactions-->
<div class="modal fade" id="editTransaction" tabindex="-1" role="dialog" aria-labelledby="editTransaction" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">  
        <div class="modal-body">
         <form method="POST" action="{{ route('transactions.update',$transaction->id) }}">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="transaction_type">Seleccione el tipo de transacción:</label>
                <select class="form-control" required name="transaction_type" id="transaction_type">
                    @forelse ($transactions_type as $type)
                        <option value="{{$type->id}}">{{$type->description}}</option>
                    @empty
                        <option value="">No hay datos disponibles</option>
                    @endforelse
                </select>
            </div>
            
             <div class="form-group">
                <label for="accountO">Seleccione la cuenta objetiva:</label>
                <select class="form-control" required name="accountO" id="accountO">
                    @forelse ($accounts as $account)
                        <option value="{{$account->id}}">{{$account->name}}</option>
                    @empty
                        <option value="">No hay datos disponibles</option>
                    @endforelse
                </select>
            </div>
           <!-- <div class="form-group">
                <label for="date">Date:</label>
                <br>
                <input class="form-control" required type="datetime" name="date" id="date">
            </div>  -->
              <div class="form-group">
                <label for="amount">Cantidad:</label>
                <br>
              <input class="form-control" required type="number" name="amount" id="amount" value="{{$transaction->amount}}">
              </div>
            <div class="form-group">
                <label for="formGroupExampleInput">Descripción:</label>
                <textarea class="form-control"  name="description" id="description" cols="30" rows="10">{{$transaction->detail}}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-info">Crear</button>
                <a class="btn btn-lg btn-danger" data-dismiss="modal">Cancelar</a>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>


<!--Modal to delete transactions-->
 <div class="modal fade" id="deleteTransaction" tabindex="-1" role="dialog" aria-labelledby="deleteTransaction" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          
        <h5 class="modal-title" id="exampleModalLabel">{{$transaction->detail}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        ¿De verdad quieres eliminar esta cuenta?
        </div>
        <div class="modal-footer">
            <form action="{{ route('transactions.destroy', $transaction->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <button class="btn btn-success" type="submit">Confirmar</button>
              <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection