project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/login', function () {
    return view('auth/login');
});

Route::get('/register', function () {
    return view('auth/register');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/settings', 'UserController@index')->name('settings')->middleware('auth');
Route::get('/categories', 'CategoryController@index')->name('categories')->middleware('auth');
Route::get('/shareds', 'HomeController@shareds')->name('shareds')->middleware('auth');


Route::get('/reports/lastmonth', 'ReportsController@lastmonth')->name('LM')->middleware('auth');
Route::get('/reports/between', 'ReportsController@between_two_dates')->name('BTD')->middleware('auth');
Route::get('/reports/last_year', 'ReportsController@lastyear')->name('LY')->middleware('auth');

Route::post('/reports/between', 'ReportsController@loadBetween')->name('loadbetween')->middleware('auth');
Route::post('/reports/lastmonth', 'ReportsController@search_by_month')->name('lastmonth')->middleware('auth');
Route::post('/reports/last_year', 'ReportsController@search_by_year')->name('lastyear')->middleware('auth');
Route::post('/transactions', 'TransactionController@store')->middleware('auth');



Route::resource('/allows', 'UserAllowedController')->middleware('auth');
Route::resource('/accounts', 'AccountController')->middleware('auth');
Route::resource('/categories', 'CategoryController')->middleware('auth');
Route::resource('/currencies', 'CurrencyController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/local_currencies', 'SetCurrenciesController')->middleware('auth');
Route::resource('/graph', 'GraphController')->middleware('auth');


Route::get('/share', function (Request $request) {
    return view('accounts.share');
})->name('share')->middleware('auth');
Route::get('/loading', function () {
return view('layouts.loader');
})->name('loading')->middleware('auth');

project/app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    public $timestamps = false;
    protected $fillable = ['id', 'name', 'symbol', 'description', 'active'];
}

project/app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Currency;
use App\Models\Account;
use Auth;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::User();
        $account = Account::where('id_owner', $user->id);
        $currenciesA = Currency::where([
            ['id_user', $user->id],
            ['active',true]
            ])->get();
        return view('currencies.index',compact('currenciesA','account','user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::User();
        $currency = new Currency();
        $currency->name             = request('name');
        $currency->symbol           = request('symbol');
        $currency->description      = request('description');
        $currency->id_user          = $user->id;
        $currency->active           = 'true';
        $currency->save();
        
        return redirect('currencies')->with('message', 'Su cuenta a sido creada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $currency = Currency::where('id', $id)->firstOrFail();
        return view('currencies.show',compact('currency'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $currency = Currency::where('id', $id)->firstOrFail();
        $currency->update($request->all());
        $currency->save();
        return redirect('currencies');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $currency = Currency::where('id', $id)->firstOrFail();
        $currency->active = false;
        $currency->update();
        return redirect('currencies');
    }

 /*   public function setcurrency($id){
        dd($id);
    }
*/
}

project/resources/views/currencies/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div class="container-fluid" >
      <div class="row">
          <div class="col-md-4">
          </div>
                <div class="container">    
                  <h3>Tus monedas</h3>
                      <div class="card-group owner">
                      <div class="row">
                        @forelse ($currenciesA as $currencie)
                      <a href="{{route('currencies.show', $currencie->id)}}" >
                        <div class="card-header">
                          <h3>{{ $currencie->symbol }}</h3> 
                       </div>
                        <div class="card-body">
                            <h3>{{ $currencie->name }}</h3>
                        </div>
                      </a>    
              &nbsp;
              @empty
              <div class="empty">
                  <h4 class="container-title">No hay datos</h4>
              </div>            
              @endforelse
                      </div>
                  </div>
                  <div class="col-md-4">    
              <a href="" class="btn-lg  btn-primary" data-toggle="modal" data-target="#createCurrencie">Agregar una moneda</a>
             </div>
              </div>
      </div>
  </div>
@endsection

<!--Action Modal -->
<div class="modal fade" id="currencieAction" tabindex="-1" role="dialog" aria-labelledby="currencieAction" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
              <h3>Elija la acción deseada</h3>  
      </div>
      <div class="modal-body">
         <a class="btn-lg btn-success"data-toggle="modal" data-dismiss="modal" data-target="#editCurrencie">Editar</a>
         <a  class="btn-lg btn-danger" data-toggle="modal" data-dismiss="modal" data-target="#deleteCurrencie">Eliminar</a>
        </div>
    </div>
  </div>
</div>

  <!-- Modal to create currencies-->
<div class="modal fade" id="createCurrencie" tabindex="-1" role="dialog" aria-labelledby="createCurrencie" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">  
        <div class="modal-body">
         <form method="POST" action="{{ route('currencies.store') }}">
            @csrf
            <div class="form-group">
                <label for="name">Nombre:</label>
                <input required type="text" required class="form-control" name="name" id="name">
            </div>
            <div class="form-group">
                <label for="symbol">Simbolo:</label>
                <input required type="text" required class="form-control" name="symbol" id="symbol">
            </div>
            <div class="form-group">
                <label for="description">Descripción:</label>
                <br>
                <textarea name="description" id="description" cols="30" rows="10"></textarea>
                <input type="hidden" name="id_user" value="{{ $user->id }}">
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-lg btn-info" value="Crear"/>
                <a class="btn btn-lg btn-danger" href="" data-dismiss="modal"> Cancelar</a>
            </div>
        </form>
        </div>
      </div>
    </div>
  </div>
</div>

project/resources/views/currencies/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col">
           <form method="POST" action="{{ route('local_currencies.update',$currency->id)}}">
                  @csrf
                  @method('PUT')
           </form> 
        </div>
    <div class="col-6">
      <form method="POST" action="{{ route('currencies.update',$currency->id) }}">
              @csrf
              @method('PUT')
             <div class="form-group">
                <label for="name">Nombre:</label>
                <input required type="text" required class="form-control" name="name" id="name" value="{{$currency->name}}">
            </div>
            <div class="form-group">
                <label for="symbol">Simbolo:</label>
                <input required type="text" required class="form-control" name="symbol" id="symbol" value="{{$currency->symbol}}">
            </div>
            <div class="form-group">
                <label for="description">Descripción:</label>
                <br>
                <textarea name="description" id="description" cols="30" rows="10">{{$currency->description}}</textarea>
                <input type="hidden" name="id_user" value="{{ $currency->id }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-success">Actualizar</button>
                <a href="" class="btn btn-lg btn-dark" data-toggle="modal" data-target="#deleteCurrencie">Eliminar</a>
                <a type="button" href="{{ route('currencies.index') }}"class="btn btn-lg btn-danger" >Cancelar</a> 
                </div>
          </form>
    </div>
     <div class="col">
    </div>
</div>
@endsection
 

 <!--Modal to confirm the deletion of Currencie-->
  <div class="modal fade" id="deleteCurrencie" tabindex="-1" role="dialog" aria-labelledby="deleteCurrencie" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
         <h3>{{$currency->name}}</h3>
        <div class="modal-header">
          
        <h5 class="modal-title" id="exampleModalLabel">{{$currency->name}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        ¿De verdad quieres eliminar esta cuenta?
        </div>
        <div class="modal-footer">
            <form action="{{ route('currencies.destroy', $currency->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <button class="btn btn-success" type="submit">Confirmar</button>
              <a href="" class="btn btn-danger">Cancelar</a> 
            </form>
        </div>
      </div>
    </div>
  </div>