project/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Route::get('/login', function () {
    return view('auth/login');
});

Route::get('/register', function () {
    return view('auth/register');
});

Auth::routes();

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('/settings', 'UserController@index')->name('settings')->middleware('auth');
Route::get('/categories', 'CategoryController@index')->name('categories')->middleware('auth');
Route::get('/shareds', 'HomeController@shareds')->name('shareds')->middleware('auth');


Route::get('/reports/lastmonth', 'ReportsController@lastmonth')->name('LM')->middleware('auth');
Route::get('/reports/between', 'ReportsController@between_two_dates')->name('BTD')->middleware('auth');
Route::get('/reports/last_year', 'ReportsController@lastyear')->name('LY')->middleware('auth');

Route::post('/reports/between', 'ReportsController@loadBetween')->name('loadbetween')->middleware('auth');
Route::post('/reports/lastmonth', 'ReportsController@search_by_month')->name('lastmonth')->middleware('auth');
Route::post('/reports/last_year', 'ReportsController@search_by_year')->name('lastyear')->middleware('auth');
Route::post('/transactions', 'TransactionController@store')->middleware('auth');



Route::resource('/allows', 'UserAllowedController')->middleware('auth');
Route::resource('/accounts', 'AccountController')->middleware('auth');
Route::resource('/categories', 'CategoryController')->middleware('auth');
Route::resource('/currencies', 'CurrencyController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/local_currencies', 'SetCurrenciesController')->middleware('auth');
Route::resource('/graph', 'GraphController')->middleware('auth');


Route::get('/share', function (Request $request) {
    return view('accounts.share');
})->name('share')->middleware('auth');
Route::get('/loading', function () {
return view('layouts.loader');
})->name('loading')->middleware('auth');

project/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('home') }}">
                    {{ config('app.name') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @guest
                            
                    @else
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="{{ route('home') }}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Cuentas
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{{ route('accounts.create') }}">Nueva cuenta</a>
                                    <a class="dropdown-item" href="{{ route('home') }}"> <i></i> Tus cuentas</a>
                                    <a class="dropdown-item" href="{{ route('shareds') }}"> <i></i> Cuentas compartidas</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="{{ route('home') }}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Monedas
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{{ route('currencies.index') }}">Administrar monedas</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="{{ route('home') }}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Reportes
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{{ route('BTD') }}">Entre Fechas</a>
                                    <a class="dropdown-item" href="{{ route('LM') }}">Último mes</a>
                                    <a class="dropdown-item" href="">Calendario mensual</a>
                                    <a class="dropdown-item" href="{{ route('LY') }}">Último año</a>
                                </div>
                            </li>
                        </ul>
                    @endguest

                    

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Cerrar Sesión') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @include('errors.flash-message')
        <main class="py-4">
            
            @yield('content')
        </main>
        <footer>
            <!-- Scripts -->
            <script type="text/javascript" src="https://code.jquery.com/jquery-1.9.1.js"></script>
            <script src="{{ asset('js/app.js') }}" defer></script>
        </footer>
    </div>
</body>
</html>

project/resources/views/layouts/loader.blade.php
@extends('layouts.app')
@section('content')
<header>
    <link href="{{ asset('css/loader.css') }}" rel="stylesheet">
</header>

<div id="loader-wrapper">
    <div id="loader"></div>
</div>
<footer>
    <script type="text/javascript" src="{{ asset('js/loader.js') }}" defer></script>
</footer>
@endsection